Loading rhel8/default-amp
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 libpciaccess/0.16/gcc-9.4.0-6fonbj6
    libiconv/1.16/gcc-9.4.0-ahebbov libxml2/2.9.12/gcc-9.4.0-gnknt5e
    ncurses/6.2/gcc-9.4.0-aiirok7 hwloc/2.5.0/gcc-9.4.0-7sqomga
    libevent/2.1.12/gcc-9.4.0-hgny7cm numactl/2.0.14/gcc-9.4.0-52dwc6n
    cuda/11.4.0/gcc-9.4.0-3hnxhjt gdrcopy/2.2/gcc-9.4.0-e4igtfp
    knem/1.1.4/gcc-9.4.0-bpbxgva libnl/3.3.0/gcc-9.4.0-whwhrwb
    rdma-core/34.0/gcc-9.4.0-5eo5n2u ucx/1.11.1/gcc-9.4.0-lktqyl4
    openmpi/4.1.1/gcc-9.4.0-epagguv
Changed directory to /rds/user/ar2217/hpc-work/L65/clrs-ls65.

JobID: 0
======
Time: Mon Feb 19 15:00:57 GMT 2024
Running on master node: gpu-q-31
Current directory: /rds/user/ar2217/hpc-work/L65/clrs-ls65

Nodes allocated:
================
gpu-q-31

numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
python -m clrs.examples.run --checkpoint_path ./checkpoints/0 --processor_type mpnn_l2 --regularisation_weight 0.0 --checkpoint_path /tmp/CLRS30/0 --dataset_path /tmp/CLRS30/0 > logs/out.0

2024-02-19 15:01:04.697040: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-19 15:01:04.697206: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-19 15:01:04.970509: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-19 15:01:08.675401: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/ar2217/.conda/envs/env_L65/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ar2217/.conda/envs/env_L65/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/rds/user/ar2217/hpc-work/L65/clrs-ls65/clrs/examples/run.py", line 131, in <module>
    save_path = FLAGS.checkpoint_path #"/Users/ariellerosinski/My Drive/Cambridge/L65 Geometric DL/Project/Code" #'/tmp/CLRS30/
  File "/home/ar2217/.conda/envs/env_L65/lib/python3.9/site-packages/absl/flags/_flagvalues.py", line 481, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --checkpoint_path before flags were parsed.
